services:
  streamlit:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: streamlit
    command: python3 runner.py
    ports:
      - 8501:8501
    volumes:
      - .:/backend