services:
#  app:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    image: backend
#    container_name: backend
#    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --workers 4
#    ports:
#      - 8000:8000
#    volumes:
#      - .:/backend
  streamlit:
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: streamlit
    command: python3 runner.py
    ports:
      - 8501:8501
    volumes:
      - .:/backend
